name: Test
on: 
  pull_request:
  push:
    branches:
      - main
      - npr
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create .env file
      run: |
          touch .env
          echo GMAPS_KEY=${{ secrets.GOOGLE_KEY }} >> .env
          echo NPR_KEY=${{ secrets.NPR_KEY }} >> .env
          cat .env
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.13
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
